version: "3.8"
services:
#  cadvisor:
#    image: unibaktr/cadvisor
#    container_name: cadvisor
#    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
#    ports:
#      - 8080:8080
#    volumes:
#      - /:/rootfs:ro 
#      - /var/run:/var/run:ro 
#      - /sys:/sys:ro 
#      - /var/lib/docker/:/var/lib/docker:ro 
#      - /dev/disk/:/dev/disk:ro

  appdaemon:
    container_name: appdaemon
    image: appdaemon:latest
    ports:
      - 5050:5050
    volumes:
      - /opt/appdaemon/conf:/conf
    restart: on-failure
    depends_on:
      - homeassistant
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"

#  grafana:
#    container_name: grafana
#    image: proxx/grafana-armv7
#    user: "1000"
#    ports:
#      - 3000:3000
#    volumes:
#      - /opt/grafana:/etc/grafana:rw
#      - /opt/grafana:/var/lib/grafana:rw
#      - /etc/timezone:/etc/timezone:ro
#    restart: on-failure
#    depends_on:
#      - influxdb

#  influxdb:
#    container_name: influxdb
#    image: influxdb
#    ports:
#      - 8086:8086
#    volumes:
#      - /opt/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
#      - /opt/influxdb:/var/lib/influxdb
#    restart: on-failure
#    healthcheck:
#      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
#      interval: 30s
#      timeout: 1s
#      retries: 24

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi2-homeassistant:0.108.9
    network_mode: "host"
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: on-failure
#    depends_on:
#      - influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"

  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /opt/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no" # because the exit code(s) are wrong

  organizr:
    container_name: organizr
    image: lsioarmhf/organizr
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/organizr:/config:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - PGID=1000
      - PUID=1000
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5


